export const title = "Welcome to American Pondering";

export const introHeading = "Honoring 250 Years of Service: A New Reflection Begins";
export const introParagraph = "On June 14, 1775, the Continental Congress formed the United States Army — a force born not out of power, but of purpose. For 250 years, the Army has stood as a living promise: to defend liberty, uphold the Constitution, and serve with honor.\n\nThis year, as the nation commemorates a quarter-millennium of that legacy, a new artistic series quietly emerges: American Pondering™.\n\nSet for its inaugural release on this historic anniversary, American Pondering™ is more than a collection of paintings — it is a meditative journey through the moral weight, internal struggle, and timeless vision carried by those who shaped our nation's course. It begins with a silent tribute — not to battles, but to the burden of leadership and the still moments before action.\n\nWhile the image itself remains unrevealed, its soul echoes the founding heartbeat of the Army — the humility, duty, and resolve of America's first commander-in-chief, and the visionaries who followed. This project does not seek to dramatize history but to give it quiet voice.\n\nAs the Army turns 250, American Pondering™ invites you to reflect, remember, and re-engage with the spirit that still calls us to serve something greater than ourselves.\n\nFrom foundation to future — a nation worth pondering.";

export const artistIntroHeading = "Kevin Petrocelli - Creator of American Pondering™";
export const artistIntroParagraph = "Kevin Petrocelli is a career law enforcement leader, lifelong public servant, and passionate student of American history. With decades of experience serving communities and leading with integrity, Kevin brings a unique depth of perspective to his creative pursuits — combining his background in leadership with a reverence for the foundational ideas that shaped the nation.\n\nHe is the creator of American Pondering™, an emerging fine art and narrative series that explores the quiet strength, internal reflection, and enduring legacy of America's most formative figures and moments. What began as a single, inspired image has grown into a larger vision: a body of work that will evolve over time — honoring the character, sacrifice, and spirit of those who helped shape the nation.\n\nRooted in personal reflection and sparked by a visit to George Washington's Mount Vernon in 2010, Kevin's journey with American Pondering™ is just beginning. Each release will build on the last, contributing to a growing tribute that spans from Foundation to Future™.\n\nHis work invites Americans not just to remember history — but to ponder what it asks of us today.";

export const teaserHeading = "Teaser: The Silence Before the Reveal";
export const teaserParagraph = "Something thoughtful is stirring. A shadow at dawn. A quill poised in hand. A reflection held longer than usual.\n\nAmerican Pondering is a new fine art series that captures the quiet moments of American leaders as they consider the weight of liberty, unity, and sacrifice.\n\nNo full reveals. Not yet. But the first subject is waiting to meet the public. Coming June 14th.";

export const connectionHeading = "Anniversary Connection: 250 Years of Reflection";
export const connectionParagraph = "2025 marks the 250th anniversary of the United States Army—a legacy of service, strength, and sacrifice.\n\nThe first release of American Pondering honors this moment. Without showing his full portrait just yet, our opening figure reflects the burden of command and the quiet strength of early American leadership.\n\nThis series aims to bring 250 stories to life, starting where the Army began: in 1775, with a commander who set the tone for a new republic.\n\nPrepare for a soft launch that honors the Army's past while hinting at the visual legacy to come.";